apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: data-volume-SIZEg-INST
spec:
  capacity:
    storage: SIZEGi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gluster-stor-cls-test
  gcePersistentDisk:
    fsType: xfs
    pdName: pd-ssd-disk-SIZEg-INST

